name: tags
channels:
  - defaults
  - pypi
dependencies:
  - python>=3.7
  - astroid==2.2.5
  - certifi==2019.6.16
  - isort==4.3.21
  - joblib==0.13.2
  - lazy-object-proxy==1.4.2
  - mccabe==0.6.1
  - mkl-service==2.3.0
  - numpy==1.16.5
  - pandas==0.25.1
  - pip=19.2.2=py37_0
  - pip:
      - idna==2.8
      - chardet==3.0.4
      - spotipy==2.4.4
      - requests==2.22.0
      - urllib3==1.25.3
  - pylint==2.3.1
  - python-dateutil==2.8.0
  - pytz==2019.2
  - scikit-learn==0.21.2
  - scipy==1.3.1
  - six==1.12.0
  - wrapt==1.11.2
